import { Term } from './types';

export const TERMS: Term[] = [
  {
    id: 'dfma',
    term: 'DfMA',
    korean: '제조 및 조립을 위한 설계',
    category: 'BIM / Modular',
    definition: 'Design for Manufacture and Assembly: A design approach that focuses on ease of manufacture and efficiency of assembly.',
    simpleExplanation: '공장에서 만들기 쉽고 현장에서 조립하기 편하게 처음부터 설계하는 방식입니다.',
    undergraduateExplanation: '건축물을 부품화하여 공장에서 생산(Manufacture)하고 현장에서 조립(Assembly)하기 최적화된 설계를 의미합니다. 기존의 현장 중심 시공에서 벗어나 제조업의 효율성을 건축에 도입하는 핵심 개념입니다.',
    graduateExplanation: '건설 산업의 생산성 향상을 위해 부품의 표준화, 단순화, 모듈화를 설계 단계에서부터 고려하는 통합 프로세스입니다. BIM 데이터와 연계되어 자동화 생산 라인과의 정밀한 인터페이스를 구축하는 것이 연구의 핵심입니다.',
    practicalExplanation: '현장 인건비 상승과 숙련공 부족 문제를 해결하기 위한 실무적 대안입니다. 자재 낭비를 줄이고 공기를 단축시키며, 현장 작업을 최소화하여 안전 사고를 예방하는 데 중점을 둡니다.',
    academicExplanation: 'Construction 4.0의 핵심 전략으로서, 건축 설계와 시공의 수직적 통합을 가능하게 하는 방법론입니다. 부품 간의 위상 관계(Topology)와 조립 순서 최적화 알고리즘 등이 주요 학술적 논의 대상입니다.',
    similarTerms: ['Modular Design', 'Prefabrication'],
    relatedTerms: ['BIM', 'OSC (Off-Site Construction)', 'Supply Chain Management'],
    exampleSentence: 'Implementing DfMA principles in the early design phase significantly reduced the on-site assembly time by 30%.'
  },
  {
    id: 'tolerance',
    term: 'tolerance',
    korean: '공차 / 허용 오차',
    category: 'Construction Management',
    definition: 'The allowable amount of variation of a specified quantity, especially in the dimensions of a machine or part.',
    simpleExplanation: '설계된 치수와 실제 만들어진 치수 사이의 허용 가능한 차이입니다.',
    undergraduateExplanation: '이론적인 설계 치수와 실제 시공된 결과물 사이에는 항상 차이가 발생합니다. 이때 구조적 안전이나 기능에 문제가 없는 수준의 오차 범위를 공차라고 합니다.',
    graduateExplanation: '부재 간의 조립성(Fit-up)을 확보하기 위한 통계적 변동 범위입니다. 특히 프리캐스트 콘크리트나 철골 구조물에서 누적 오차(Stack-up tolerance) 관리는 시공 정밀도 확보의 핵심 연구 분야입니다.',
    practicalExplanation: '현장에서 검측 시 합격/불합격을 판단하는 기준입니다. 시방서에 명시된 허용 오차를 벗어나면 재시공이나 보강이 필요하므로, 정밀한 계측 장비를 통한 관리가 필수적입니다.',
    academicExplanation: '품질 관리(Quality Control) 이론에서 변동성(Variability)의 정량적 한계를 정의합니다. 최근에는 3D 스캔 데이터를 활용한 오차 분석 및 디지털 트윈 기반의 실시간 오차 보정 기술이 연구되고 있습니다.',
    similarTerms: ['Allowable Error', 'Margin'],
    relatedTerms: ['Precision', 'Quality Control', '3D Scanning'],
    exampleSentence: 'The tolerance for the precast concrete panel alignment was strictly limited to ±5mm to ensure proper joint sealing.'
  },
  {
    id: 'shop-drawing',
    term: 'shop drawing',
    korean: '시공 상세도 / 샵 드로잉',
    category: 'Construction Practice',
    definition: 'A drawing or set of drawings produced by the contractor, supplier, manufacturer, subcontractor, or fabricator.',
    simpleExplanation: '설계 도면을 바탕으로 실제로 어떻게 만들지 아주 자세하게 그린 도면입니다.',
    undergraduateExplanation: '설계자가 작성한 설계도면(Design Drawing)은 개념적인 정보를 담고 있습니다. 시공자가 이를 바탕으로 실제 제작 및 설치가 가능하도록 부재의 연결 방식, 치수 등을 상세히 그린 도면이 샵 드로잉입니다.',
    graduateExplanation: '설계 의도(Design Intent)를 실제 물리적 객체로 구현하기 위한 기술적 해석 과정의 산물입니다. BIM 환경에서는 LOD(Level of Development) 400 수준의 모델이 샵 드로잉의 역할을 대체하거나 보완합니다.',
    practicalExplanation: '현장에서 작업자가 보고 만드는 가장 중요한 도면입니다. 철근 배근도, 창호 상세도 등이 대표적이며, 감리자의 승인을 득해야 실제 제작에 들어갈 수 있습니다.',
    academicExplanation: '설계와 시공 사이의 정보 전달(Information Exchange) 매커니즘을 연구하는 대상입니다. 디지털 패브리케이션(Digital Fabrication) 시대에는 샵 드로잉 없이 모델에서 바로 제작으로 이어지는 모델 기반 워크플로우가 논의됩니다.',
    similarTerms: ['Working Drawing', 'Fabrication Drawing'],
    relatedTerms: ['Design Intent', 'LOD', 'Approval Process'],
    exampleSentence: 'The steel fabricator submitted the shop drawings for the complex roof truss for the engineer\'s review and approval.'
  },
  {
    id: 'erection-sequence',
    term: 'erection sequence',
    korean: '설치 순서 / 건립 순서',
    category: 'Construction Management',
    definition: 'The specific order in which structural components are assembled or installed on site.',
    simpleExplanation: '건물 뼈대를 어떤 순서로 세울지 정한 계획입니다.',
    undergraduateExplanation: '철골이나 프리캐스트 부재를 크레인으로 들어 올려 조립할 때, 구조적 안정성을 유지하면서 가장 효율적으로 작업할 수 있는 순서를 말합니다.',
    graduateExplanation: '시공 단계별 구조 해석(Construction Stage Analysis)과 밀접하게 연계된 프로세스입니다. 각 단계에서의 하중 지지 능력과 기하학적 형상 유지를 최적화하는 경로를 탐색하는 것이 중요합니다.',
    practicalExplanation: '장비(크레인)의 배치, 자재의 반입 순서, 작업자의 안전과 직결되는 실무 계획입니다. 잘못된 순서는 구조물 붕괴나 공기 지연을 초래할 수 있습니다.',
    academicExplanation: '4D BIM 시뮬레이션을 통한 시공 최적화의 핵심 변수입니다. 유전 알고리즘이나 강화 학습을 활용하여 최적의 건립 시퀀스를 자동 생성하는 연구가 활발히 진행 중입니다.',
    similarTerms: ['Installation Order', 'Construction Sequence'],
    relatedTerms: ['4D BIM', 'Logistics', 'Structural Stability'],
    exampleSentence: 'The erection sequence of the modular units was optimized to minimize crane movements and ensure structural stability during construction.'
  },
  {
    id: 'joint-detail',
    term: 'joint detail',
    korean: '접합부 상세',
    category: 'Architecture / Structure',
    definition: 'The detailed design of the connection between two or more structural or architectural elements.',
    simpleExplanation: '서로 다른 재료나 부품이 만나는 부분을 어떻게 연결할지 정한 상세한 계획입니다.',
    undergraduateExplanation: '기둥과 보, 벽과 바닥 등 서로 다른 부재가 만나는 지점의 연결 방식입니다. 볼트 체결, 용접, 일체 타설 등 다양한 방식이 있으며 구조적 성능과 방수, 단열 성능에 큰 영향을 미칩니다.',
    graduateExplanation: '응력 집중(Stress Concentration)과 에너지 분산이 일어나는 핵심 영역입니다. 특히 지진 하중 하에서의 연성(Ductility) 확보를 위한 접합부 거동 해석 및 실험적 검증이 주요 연구 주제입니다.',
    practicalExplanation: '현장에서 하자가 가장 많이 발생하는 지점입니다. 누수, 결로, 균열 등이 접합부 처리 미숙에서 비롯되므로, 시공 상세도에서 가장 주의 깊게 검토해야 할 부분입니다.',
    academicExplanation: '이종 재료 간의 인터페이스(Interface) 관리 및 성능 구현을 위한 마이크로 레벨의 설계입니다. 최근에는 3D 프린팅을 활용한 복잡한 형상의 커스텀 접합부 설계 연구가 주목받고 있습니다.',
    similarTerms: ['Connection Detail', 'Interface Detail'],
    relatedTerms: ['Structural Integrity', 'Waterproofing', 'Thermal Bridge'],
    exampleSentence: 'The joint detail between the curtain wall and the floor slab required careful consideration of thermal expansion and fire stopping.'
  },
  {
    id: 'constructability',
    term: 'constructability',
    korean: '시공성',
    category: 'Construction Management',
    definition: 'The ease and efficiency with which a project can be built, considering the design and site conditions.',
    simpleExplanation: '설계된 건물을 실제로 얼마나 쉽고 효율적으로 지을 수 있는지를 말합니다.',
    undergraduateExplanation: '설계안이 실제 현장에서 구현 가능한지, 그리고 얼마나 경제적이고 안전하게 지어질 수 있는지를 평가하는 지표입니다. "지을 수 있는 설계"를 하는 것이 핵심입니다.',
    graduateExplanation: '설계 지식과 현장 경험을 통합하여 프로젝트 목표를 달성하는 최적화 프로세스입니다. 시공성 검토(Constructability Review)는 초기 단계에서 비용 절감과 품질 향상을 이끄는 핵심 도구입니다.',
    practicalExplanation: '설계 도면의 오류를 사전에 찾아내고, 현장의 장비나 인력 여건에 맞는 공법을 제안하는 활동입니다. 시공성이 낮은 설계는 잦은 설계 변경과 공사비 증액의 원인이 됩니다.',
    academicExplanation: '지식 관리(Knowledge Management) 측면에서 시공 지식의 전방 배치(Front-end Loading)를 의미합니다. BIM 기반의 가상 시공(Virtual Construction)을 통해 시공성을 정량적으로 평가하는 프레임워크 연구가 많습니다.',
    similarTerms: ['Buildability'],
    relatedTerms: ['Value Engineering (VE)', 'Pre-construction Services', 'BIM Coordination'],
    exampleSentence: 'A constructability review during the schematic design phase identified several potential conflicts between the structural and MEP systems.'
  },
  {
    id: 'modular-construction',
    term: 'modular construction',
    korean: '모듈러 건설',
    category: 'Construction Method',
    definition: 'A process in which a building is constructed off-site, under controlled plant conditions, using the same materials and designing to the same codes and standards as conventionally built facilities.',
    simpleExplanation: '건물의 방이나 거실 같은 단위를 공장에서 미리 다 만든 다음, 현장에서는 레고처럼 쌓아 올리는 방식입니다.',
    undergraduateExplanation: '건축물의 70~80% 이상을 공장에서 박스 형태로 제작한 후 현장으로 운반하여 조립하는 공법입니다. 현장 작업을 획기적으로 줄일 수 있는 탈현장 건설(OSC)의 대표 주자입니다.',
    graduateExplanation: '건설의 산업화(Industrialization of Construction)를 실현하는 플랫폼 기반 생산 방식입니다. 모듈 간의 접합부 성능, 장거리 운송 시의 동적 안정성, 고층화 기술 등이 주요 연구 과제입니다.',
    practicalExplanation: '공기 단축이 절실한 프로젝트(기숙사, 병원, 군 시설 등)에 매우 유리합니다. 공장 생산을 통해 균일한 품질 확보가 가능하며, 소음과 먼지 등 현장 민원을 최소화할 수 있습니다.',
    academicExplanation: '공급망 관리(SCM)와 린 건설(Lean Construction) 이론이 결합된 생산 시스템입니다. 모듈러 건물의 생애주기 탄소 배출량 분석 및 해체 후 재사용(Design for Disassembly) 가능성에 대한 연구가 활발합니다.',
    similarTerms: ['Volumetric Construction', 'Unitized Construction'],
    relatedTerms: ['OSC', 'DfMA', 'Supply Chain Management'],
    exampleSentence: 'Modular construction allowed the hotel to open six months earlier than a traditional build would have permitted.'
  },
  {
    id: 'prefabrication',
    term: 'prefabrication',
    korean: '프리패브리케이션 / 사전 제작',
    category: 'Construction Method',
    definition: 'The practice of assembling components of a structure in a factory or other manufacturing site, and transporting complete assemblies or sub-assemblies to the construction site where the structure is to be located.',
    simpleExplanation: '건물에 들어갈 부품들을 미리 공장에서 만들어 오는 것입니다.',
    undergraduateExplanation: '현장에서 직접 만들지 않고 공장에서 미리 제작해 온 부재(PC 콘크리트, 철골 부재 등)를 사용하는 것을 말합니다. 모듈러 건설보다는 좀 더 넓은 의미로 부품 단위의 제작을 포함합니다.',
    graduateExplanation: '현장 작업의 공장화(Off-site Manufacturing)를 통한 생산성 혁신 전략입니다. 부재의 표준화와 대량 생산을 통해 원가를 절감하고 품질의 변동성을 제어하는 것이 목적입니다.',
    practicalExplanation: '철근 가공, 배관 유닛 제작 등을 공장에서 수행하여 현장 투입 인력을 줄이는 실무적 기법입니다. 정밀도가 높고 기상 조건에 구애받지 않고 제작할 수 있다는 장점이 있습니다.',
    academicExplanation: '건설 자동화(Construction Automation)의 전제 조건입니다. 로봇 제작(Robotic Fabrication) 기술과 연계되어 복잡한 비정형 부재를 효율적으로 생산하는 디지털 패브리케이션 연구가 활발합니다.',
    similarTerms: ['Off-site Fabrication', 'Pre-assembly'],
    relatedTerms: ['OSC', 'DfMA', 'Industrialized Construction'],
    exampleSentence: 'The prefabrication of bathroom pods ensured high-quality finishes and reduced the number of trades required on-site.'
  },
  {
    id: 'method-statement',
    term: 'method statement',
    korean: '작업 절차서 / 시공 계획서',
    category: 'Construction Management',
    definition: 'A document that details the way a specific task or process will be carried out, including health and safety risks.',
    simpleExplanation: '어떤 작업을 어떤 순서로, 어떤 장비를 써서 안전하게 할지 적어놓은 설명서입니다.',
    undergraduateExplanation: '특정 공종(예: 터파기, 콘크리트 타설)을 수행하기 위한 구체적인 방법, 순서, 투입 인력 및 장비, 안전 대책 등을 기술한 문서입니다.',
    graduateExplanation: '위험성 평가(Risk Assessment)와 시공 최적화 계획이 통합된 기술 문서입니다. 작업의 효율성과 안전성을 동시에 확보하기 위한 논리적 근거를 제시해야 합니다.',
    practicalExplanation: '발주처나 감리단에 제출하여 승인을 받아야 하는 실무 서류입니다. 사고 발생 시 법적 근거가 될 수 있으므로 매우 구체적이고 현실적으로 작성되어야 합니다.',
    academicExplanation: '시공 지식의 정형화(Formalization) 및 표준 작업 절차(SOP) 구축의 대상입니다. 최근에는 텍스트 마이닝을 통해 과거의 작업 절차서에서 위험 요인을 자동 추출하는 연구가 진행되고 있습니다.',
    similarTerms: ['Safe Work Method Statement (SWMS)', 'Construction Plan'],
    relatedTerms: ['Risk Assessment', 'Health and Safety', 'Quality Plan'],
    exampleSentence: 'Before starting the deep excavation, the contractor had to submit a detailed method statement outlining the shoring installation and monitoring plan.'
  },
  {
    id: 'as-built-drawing',
    term: 'as-built drawing',
    korean: '준공 도면',
    category: 'Construction Practice',
    definition: 'A revised set of drawings submitted by a contractor upon the completion of a project or a particular job.',
    simpleExplanation: '공사가 다 끝난 후, 실제 지어진 모습 그대로 다시 그린 도면입니다.',
    undergraduateExplanation: '공사 과정에서 설계 변경이 빈번하게 일어납니다. 처음의 설계도면과 실제 지어진 건물의 차이를 반영하여 최종적으로 작성한 도면이 준공 도면입니다.',
    graduateExplanation: '건물의 생애주기 관리(Asset Management)를 위한 기초 데이터입니다. 실제 시공된 상태(As-built condition)를 정확히 기록하여 유지관리 단계에서의 정보 신뢰성을 확보하는 것이 중요합니다.',
    practicalExplanation: '건축물 대장 등록 및 향후 유지보수, 리모델링 시 가장 중요한 근거 자료입니다. 매립된 배관의 위치 등을 정확히 기록해두지 않으면 나중에 큰 문제가 될 수 있습니다.',
    academicExplanation: '디지털 트윈(Digital Twin) 구축을 위한 실세계 데이터 동기화의 결과물입니다. 3D 스캔 데이터를 활용하여 자동으로 준공 모델을 생성하는 Scan-to-BIM 기술이 주요 연구 분야입니다.',
    similarTerms: ['Record Drawing'],
    relatedTerms: ['Facility Management (FM)', 'Scan-to-BIM', 'Life Cycle Management'],
    exampleSentence: 'The facility manager relied on the as-built drawings to locate the shut-off valves during the emergency pipe repair.'
  },
  {
    id: 'clash-detection',
    term: 'clash detection',
    korean: '간섭 체크',
    category: 'BIM',
    definition: 'The process of identifying where two or more building elements occupy the same space in a 3D model.',
    simpleExplanation: '3D 모델에서 파이프와 기둥이 서로 겹치거나 부딪히는 곳이 없는지 미리 찾아내는 것입니다.',
    undergraduateExplanation: 'BIM 모델을 활용하여 건축, 구조, 설비 등 서로 다른 공종의 부재들이 물리적으로 겹치는 부분을 시공 전에 찾아내는 과정입니다. 현장에서의 재시공을 막아줍니다.',
    graduateExplanation: '설계 조정(Design Coordination)의 자동화 프로세스입니다. 물리적 충돌(Hard Clash)뿐만 아니라 작업 공간 부족이나 유지관리 이격 거리 미확보(Soft Clash)까지 검토 범위에 포함됩니다.',
    practicalExplanation: 'BIM 도입의 가장 즉각적인 효과(ROI)를 볼 수 있는 부분입니다. 수백 건의 간섭을 사전에 해결함으로써 설계 변경 비용과 공기 지연 리스크를 획기적으로 줄일 수 있습니다.',
    academicExplanation: '알고리즘 기반의 기하학적 충돌 분석 및 간섭 우선순위 결정(Clash Prioritization) 연구가 핵심입니다. 수많은 간섭 중 실제로 중요한 간섭을 AI로 선별하는 기술이 연구되고 있습니다.',
    similarTerms: ['Interference Check', 'Conflict Detection'],
    relatedTerms: ['BIM Coordination', 'Navisworks', 'Design Review'],
    exampleSentence: 'Automated clash detection revealed that the main HVAC duct was intersecting with a structural steel beam, allowing for a redesign before construction.'
  },
  {
    id: 'specification',
    term: 'specification',
    korean: '시방서',
    category: 'Construction Management',
    definition: 'A detailed description of the materials, dimensions, and workmanship required for a piece of work.',
    simpleExplanation: '도면에 다 담지 못한 재료의 품질, 작업 방법, 주의사항 등을 글로 자세히 적어놓은 문서입니다.',
    undergraduateExplanation: '도면이 "어디에 무엇을" 설치할지 보여준다면, 시방서는 "어떤 품질의 재료를 어떻게" 시공할지 설명합니다. 도면과 함께 계약 문서의 핵심을 이룹니다.',
    graduateExplanation: '성능 중심 시방서(Performance Specification)와 절차 중심 시방서(Prescriptive Specification)로 나뉩니다. 프로젝트의 품질 목표를 달성하기 위한 기술적 표준과 법적 요구사항을 정의합니다.',
    practicalExplanation: '공사비 산출과 품질 검사의 기준이 됩니다. 특정 자재의 등급이나 시공 순서 등이 명시되어 있어, 시공자와 감리자 사이의 분쟁 시 가장 우선시되는 판단 근거입니다.',
    academicExplanation: '건설 정보 표준화(Standardization) 및 온톨로지(Ontology) 구축의 핵심 소스입니다. 자연어 처리(NLP)를 활용하여 시방서의 요구사항을 자동으로 추출하고 검토하는 연구가 진행 중입니다.',
    similarTerms: ['Spec', 'Technical Requirements'],
    relatedTerms: ['Contract Documents', 'Quality Assurance', 'Standardization'],
    exampleSentence: 'The project specification required that all concrete used for the foundation must reach a minimum compressive strength of 35 MPa after 28 days.'
  }
];
